### ISSUE TITLE
Browser automatically adding space in the url

### ISSUE THREAD

**Issue by IamSingh01** [AbdulRhmanAlfaifi/Fennec#10]
How do I stop the browser from adding space after the full stop while entering url, eg. "Firefox. com". It's too frustrating while entering a url and end up with the browser showing me the search results. I noticed this happens only with the fennec/firefox, I've disabled the related settings from keyboard as well to verify if it's happening due to keyboard but seems like issue is with the browser.
Please let me know if there's a solution.
Using: Openboard (keyboard)

**Comment by AbdulRhmanAlfaifi** [comment]
Hi man,
I think you are on the wrong repo 😅

**Comment by IamSingh01** [comment]
My bad

> Hi man, I think you are on the wrong repo 😅

My bad.
