### ISSUE TITLE
Fennec mount disk

### ISSUE THREAD

**Issue by b4sm** [AbdulRhmanAlfaifi/Fennec#11]
i'm trying to mount a disk then use Fennec to collect artifacts from the mounted disk, but didn't work with me.
thank you and much appreciated for your work.

**Comment by AbdulRhmanAlfaifi** [comment]
Hello!
Fennec provides four types of artifacts:
* Query (osquery)
* Command
* Collect
* Parse

With a offline system you can only use the Collect & Parse artifact types. Query & Command only work on the live system

To use the Collect & Parse artifact types on a offline system you need to modify the configuration file. Here is how:
1. Dump the configuration file from `Fennec` using:
`./fennec --show-config > conf.yaml`
2. Remove all `query` & `command` artifacts from `conf.yaml`
3. Modify the `paths` field for `collect` & `parse` by prepending the mount path for your disk image (ex. from `/var/log/**/*` to `/mount/analysis/var/log/**/*` in this example `/mount/analysis` is the mount path for the disk image)
4. Run `fennec` with the custom config:
`sudo ./fennec -c conf.yaml` 

This will work but there will be missing artifacts like `sudoers`, `users`, etc. You have to add them to the configuration file manually as `collect` or `parse` artifacts

I hope this help!
