### ISSUE TITLE
rustc 1.53.0 build fails

### ISSUE THREAD

**Issue by cteodor** [AbdulRhmanAlfaifi/Fennec#2]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
rustc 1.53.0
cargo 1.53.0
Linux u20 5.4.0-99-generic #112-Ubuntu SMP Wed Feb 2 17:13:12 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@u20:~/code/fennec.upstream$ cargo build --release
error: failed to parse manifest at `/home/ubuntu/code/fennec.upstream/Cargo.toml`
Caused by:
  feature `edition2021` is required
  consider adding `cargo-features = ["edition2021"]` to the manifest

Once added, I get another error:
  Compiling digest v0.9.0
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.10/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "derive", doc = include_str!("../README.md"))]
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling block-buffer v0.9.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

Sorry, don't know enough rust for a PR :-)

**Comment by AbdulRhmanAlfaifi** [comment]
Hi,
Try updating the stable toolchain by running:
```bash
rustup update stable
```
Then compile again
