### ISSUE TITLE
threat 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Custom { kind: Other, error: "Large file option has not been set" }' , src/lib/mod.rs:542:87 note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

### ISSUE THREAD

**Issue by sinan-lab** [AbdulRhmanAlfaifi/Fennec#8]
![image](https://user-images.githubusercontent.com/57458584/178909859-4c93d101-12ff-447b-abdb-c032888a2495.png)

threat 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Custom { kind: Other, error: "Large file option has not been set" }' , src/lib/mod.rs:542:87 note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

**Comment by AbdulRhmanAlfaifi** [comment]
Hello Sinan,
Thank you for reporting this issue. I was able to reproduce the issue which is related to the zip library. A flag must be set to enable ZIP64 (zip file larder than 4GB in size). This issue will be fixed in next release.

Thanks,
AA
